apiVersion: v1
kind: Pod
metadata:
  name: sergey-abc
  labels:
    app: sergey-abc
spec:
  containers:
    - name: ecoviz-abc
      image: segurvich/ecoviz_abc:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          nvidia.com/gpu: 1
          memory: "16Gi"  # Set memory limit to 2 GiB
        requests:
          memory: "16Gi"  # Request 1 GiB of memory
  restartPolicy: Always
  